from typing import Optional

from amaranth import *
from amaranth.build import *

from amaranth.vendor import XilinxPlatform


__all__ = ["XilinxZynqPlatform"]


class XilinxZynqPlatform(XilinxPlatform):
    """Platform for Zynq 7000 FPGAs. This platform handles the processing_system
    IP available on those FPGAs. These contain the ARM core(s), memory interfaces,
    PLLs, ..."""
    def __init__(self, *, toolchain: Optional[str]=None):
        if toolchain is None:
            toolchain = "Vivado"
        if toolchain != "Vivado":
            raise ValueError("Only Vivado toolchain is support for Zynq 7000 devices")
    
        super().__init__(toolchain=toolchain)

        self._vivado_file_templates["{{name}}.xdc"] = r"""
            # {{autogenerated}}
            {% for placer, port_name, pin_name, attrs in platform.iter_port_constraints_bits_zynq() -%}
                set_property {{placer}} {{pin_name}} [get_ports {{port_name|tcl_quote}}]
                {% for attr_name, attr_value in attrs.items() -%}
                    set_property {{attr_name}} {{attr_value|tcl_quote}} [get_ports {{port_name|tcl_quote}}]
                {% endfor %}
            {% endfor %}
            {% for net_signal, port_signal, frequency in platform.iter_clock_constraints() -%}
                {% if port_signal is not none -%}
                    create_clock -name {{port_signal.name|ascii_escape}} -period {{1000000000/frequency}} [get_ports {{port_signal.name|tcl_quote}}]
                {% else -%}
                    create_clock -name {{net_signal.name|ascii_escape}} -period {{1000000000/frequency}} [get_nets {{net_signal|hierarchy("/")|tcl_quote}}]
                {% endif %}
            {% endfor %}
            {{get_override("add_constraints")|default("# (add_constraints placeholder)")}}
        """

        self.add_resources((
            Resource("ps_clk", 0,
                Pins("E7", dir="i"), Clock(33.333e6), Attrs(
                    IOSTANDARD="LVCMOS33", FIXED_IO=True,
                ),
            ),
        ))

    def iter_port_constraints_bits_zynq(self):
        attrs: dict
        for port_name, pin_name, attrs in self.iter_port_constraints_bits():
            attrs = attrs.copy()
            fixed_io = attrs.pop("FIXED_IO", False)
            placer = "LOC" if not fixed_io else "PACKAGE_PIN"
            yield placer, port_name, pin_name, attrs


